# -*- coding: utf-8 -*-
"""Data_collection_api_F1 Mobile Racing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QxSacg5bxWjI2Q_6dR3QZeGZqJg7VYeE

# 데이터 수집

연구를 하는 과정에서 데이터 수집은 정말 중요합니다.

데이터를 수집하는 과정은 정말 다양하지만, 제가 생각하는 수집 방법은 크게 2가지 입니다.

1. 제공된 데이터 다운
ex) AI-Hub, bigkinds (뉴스 데이터 제공)

2. 데이터 직접 수집

  2.1  API가 존재하는가?
  ex) reddit, bigkinds (유료인가..?)

  2.2 다른 사람이 먼저 구현한 코드 (github)

  2.3  * 크롤링 (최후의 보루)
제공된 데이터를 다운 받을 때도 크롤링을 사용하는 경우가 존재 (너무 많을 때 Selenium을 이용해서 사람이 하는 것처럼 다운)

# google-play-scraper (API)
설치


https://play.google.com/store/games?hl=en
"""

!pip install google-play-scraper

"""# 데이터 수집"""

from google_play_scraper import Sort, reviews_all
# API에서 제공되는 데이터는 application의 모든 리뷰를 가져오는 것은 아닙니다.
# 또한 시도마다 서버에서 제공되는 데이터 개수가 달라질 수 있습니다.
# reviews_all안의 값들은 영어 데이터를 수집하기 위해 설정되어 있습니다.
raw_data = reviews_all(
    'com.codemasters.F1Mobile', # app
    # 리뷰수가 많으면 코랩에서 돌아가는데 시간 많이 걸리므로, 로컬에서 하거나 리뷰 적은 게임으로 시도
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.MOST_RELEVANT # defaults to Sort.MOST_RELEVANT
)

# 댓글, 별점, 공감수, 시간

"""# 수집된 데이터 출력"""

from pprint import pprint
pprint(raw_data[:5])

"""# 데이터 저장 (csv)"""

from google.colab import drive
drive.mount('/content/drive')

import csv

data_li = [(info['content'], info['score'], info['thumbsUpCount'], info['at']) for info in raw_data]
# 필요한 정보만 key값으로 선택해서 list 형태로 저장
# mount 과정을 통해서 자신의 구글 드라이브에 데이터를 저장합니다.
# 혹은 경로 설정없이 "application_data.csv"로 저장해도 되지만, 런타임이 끝나면 데이터가 사라질 위험이 있습니다.

with open("/content/drive/MyDrive/application_data.csv", 'wt', encoding='utf-8', newline='') as file:
        csv_writer = csv.writer(file)
        csv_writer.writerow(["contents", "star", "agree", "date"])
        # column name 지정

        for data in data_li:
            csv_writer.writerow(data)

import pandas as pd

review_df = pd.read_csv("/content/drive/MyDrive/application_data.csv")
review_df